name: Syntax

on:
  push:
    paths:
      - 'explore/*.py'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: x64

      - name: Checkout
        uses: actions/checkout@master

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        uses: suo/flake8-github-action@v1